### PR TITLE
feat: husky to easy git hook

### PR DESCRIPTION
**Pull request by ekoeryanto**
Is `npm run lint` enough?
what you think about `lint-staged`, `imagemin-lint-staged`, `prettier`, `npm run lint -- --fix` ?

### CODE REVIEW

**Comment by renestalder** [comment]
I'm not sure we should add more than needed to this starter.

Even while I use prettier in nearly all of my projects, adding prettier, husky or other opinionated workflows to the template makes it more complicated for others to adapt it to their tools.

If you say, prettier is the defacto standard of the Vue community, then it makes sense to go with it.

`lint` was part of the code I forked. I would even remove that.

On the other side, we could also make this an option during initialization.

**Comment by renestalder** [comment]
btw. you only added the husky package in your pull request, but no other code changes.

**Comment by ekoeryanto** [comment]
yes, as it's already `precommit` script defined [there](https://github.com/renestalder/nuxt-netlify-cms-starter-template/blob/aee96aa5250475c0f15d1b5dafbb939dd3611429/template/package.json#L14)

**Comment by ekoeryanto** [comment]
>we could also make this an option during initialization

Agree, that's a _nice to have_ feature in the future of the template

**Comment by renestalder** [comment]
Closing as of given reasons above to keep the decision of code linting/prettifying to the user and the template as barebone as possible. Thanks for your pull request.

**Pull request closed without merging**
